### ISSUE TITLE
Bundle time and energy?

### ISSUE THREAD

**Issue by Rillke** [xrmx/opusenc.js#1]
Hi; I created a working version: https://github.com/Rillke/opusenc.js

https://blog.rillke.com/opusenc.js/

Dependent on what you've in mind, it'd be cool to work on a single repo.

Let me know what you think about that.

**Comment by xrmx** [comment]
Hi @Rillke thanks for letting me know about your project! As you can see mine isn't finished and i haven't touched it in years, if i'll need an opus encoder i'll use yours of course. I've starred it, have fun developing it!
